POST http://localhost:8000/api-token-auth/
Content-Type: application/json

{
    "username": "test01",
    "password": "test"
}

### a31e7d9154fb9cb6e9a61fb9d29f47f45e829783

POST http://localhost:8000/api/member/
Content-Type: application/json

{
  "username": "tester02",
  "email": "test02@co.jp",
  "password": "test"
}

###
# @prompt token

GET http://localhost:8000/api/member/
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token

GET http://localhost:8000/api/booklisttype/?owner_id=0fbbe10c-3b6b-4d4d-813f-50663c83732b
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token

GET http://localhost:8000/api/booklist/?booklisttype_id=ad385e66-5135-4157-8967-aa2d6c594122
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token

GET http://localhost:8000/api/booklist/?booklisttype_id=ad385e66-5135-4157-8967-aa2d6c594122&reviewer_id=0fbbe10c-3b6b-4d4d-813f-50663c83732b
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token

GET http://localhost:8000/api/booklist/?booklisttype_id=ad385e66-5135-4157-8967-aa2d6c594122&reviewer_id=0fbbe10c-3b6b-4d4d-813f-50663c83732b&mode=edit
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token

GET http://localhost:8000/api/booklist/?booklisttype_id=ad385e66-5135-4157-8967-aa2d6c594122&reviewer_id=0fbbe10c-3b6b-4d4d-813f-50663c83732b&mode=display
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token
# 評価先本棚所有者：aaa
# 評価者：test01

GET http://localhost:8000/api/booklist/?member_id=279c1610-6602-49da-b29e-e21387c52170&reviewer_id=0fbbe10c-3b6b-4d4d-813f-50663c83732b&mode=display
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token

GET http://localhost:8000/api/booklist/?booklisttype_id=ad385e66-5135-4157-8967-aa2d6c594122&reviewer_id=0fbbe10c-3b6b-4d4d-813f-50663c83732b&mode=admin
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token
# 評価先本棚所有者：aaa
# 評価者：test01

GET http://localhost:8000/api/booklist/?member_id=279c1610-6602-49da-b29e-e21387c52170&reviewer_id=0fbbe10c-3b6b-4d4d-813f-50663c83732b&mode=admin
Content-Type: application/json
Authorization: Token {{token}}


###
# @prompt token
GET http://localhost:8000/api/booklist/admin_view/?booklisttype_id=ad385e66-5135-4157-8967-aa2d6c594122
Content-Type: application/json
Authorization: Token {{token}}

###
# @prompt token

PUT http://localhost:8000/api/book/bulk_update/
Content-Type: application/json
Authorization: Token {{token}}

{
  "books": [
    {
      "id": "26d0b979-a4f7-4caf-8092-b065bb6cdd10",
      "booklist": "39e647f9-73ea-436f-b5f3-d0f7d4cae028",
      "title": "Updated Title 1",
      "description": "Updated Description 1",
      "image": "http://0.0.0.0:8000/media/example.png",
      "order": 1
    }
  ],
  "id": "39e647f9-73ea-436f-b5f3-d0f7d4cae028",
  "is_completed": true
}


### token: a31e7d9154fb9cb6e9a61fb9d29f47f45e829783
###
# @prompt token

POST http://localhost:8000/api/booklist/like/
Content-Type: application/json
Authorization: Token {{token}}

{
  "booklist_id": "ab2dc6b9-cfb8-4eaf-ab91-fd28c64b3d3b",
  "reviewer_id": "0fbbe10c-3b6b-4d4d-813f-50663c83732b",
  "like": true
}
